config/routes.rb
FoodTruckApp::Application.routes.draw do
  resources :trucks

  root :to => 'trucks#index'
end

app/models/truck.rb
class Truck < ActiveRecord::Base
  attr_accessible :name, :type_of_food
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/trucks_controller.rb
class TrucksController < ApplicationController
	def index
		@trucks = Truck.all
	end

	def show
		@truck = Truck.find(params[:id])
	end

	def new
		@truck = Truck.new
	end

	def create
		@truck = Truck.create(params[:truck])

		redirect_to trucks_path
	end

	def edit
		@truck = Truck.find(params[:id])
	end

	def update
		@truck = Truck.update(params[:id], params[:truck])

		redirect_to truck_path(@truck)
	end

	def destroy
		@truck = Truck.find(params[:id])
		@truck.destroy

		redirect_to trucks_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trucks_helper.rb
module TrucksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FoodtruckApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/trucks/edit.html.erb
<h1>Edit truck!</h1>

<%= form_for @truck do |f| %>
	<%= f.text_field :name %>
	<%= f.text_field :type_of_food %>
	<%= f.submit("edit") %>
<% end %>

<%= button_to "delete", {:controller => :trucks,
      :action => 'destroy', :id => @truck.id }, :method => :delete %>

app/views/trucks/index.html.erb
<div class="container bigbox">
	<div class="sixteen columns">
		<div class="row">
			<h1 style="margin-top: 40px">Food Trucks!</h1>
			<hr />
		</div>
	</div>

		<% @trucks.each do |truck| %>
	
		<div class="sixteen columns">
			<h3><%= truck.name %></h3><br>
			<h4><%= truck.type_of_food %></h4>
		</div>
			
	
		<div class="row"></div>
		
	<% end %>

</div>

app/views/trucks/new.html.erb
<div class="container bigbox">
	<div class="sixteen columns">
		<div class="eight columns">
			<h1>Add a new truck!</h1>
		</div>

		<%= form_for @truck do |f| %>

			<div class="eight columns">
				<ul>
					<%= f.text_field :name %>
					<%= f.text_field :type_of_food %>
				</br>
			
					<%= f.submit("add") %>
				</ul>
			</div>
		<% end %>
	</div>
</div>

app/views/trucks/show.html.erb
<div class="container bigbox">
	<div class="sixteen columns">
		<h2><%= @truck.name %></h2><br>
		<h4><%= @truck.type_of_food %></h4>
		<h5><%= link_to 'Edit', edit_truck_path(@truck.id) %></h5>
			
		<div class="row"></div>
	</div>
</div>